### ISSUE TITLE
Not working on Macbook M1

### ISSUE THREAD

**Issue by Voxer425** [mganss/CueGen#14]
Hi,

Would it be possible to get this running on Macbook M1 architecture?  Would love to use it.

Error trying this:
Error: Error occurred during creation of cues for "99993103" from "..." System.IO.FileNotFoundException: Could not find file '...'.
File name: '...'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at TagLib.File.LocalFileAbstraction.get_ReadStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()

**Comment by mganss** [comment]
It should run on macOS with Apple Silicon CPUs (M1 etc). The reference to `Win32` in the namespace name may just be for historical reasons.

Does the file exist that the exception message refers to?

**Comment by Voxer425** [comment]
Oh, thats good to hear!

The file exists in the location it is showing in the error. I run the program by "sudo chmod 777 ./CueGen.Console" and then run "./CueGen.Console". There exists whitespace in the song name.

**Comment by Voxer425** [comment]
Oh, sorry, I got it working! The file was missing. Thought it's about M1 because of the `Win32` error.
