### ISSUE TITLE
Couple of errors

### ISSUE THREAD

**Issue by NachoShaw** [mganss/CueGen#15]
Hi

Great tool. Im getting some errors. about 50% of my library throws an error-
Could not find part of the path
1172/1172Error: Error occurred during creation of cues for "9978813" from "G:/Rekordbox Tracks/Toolroom Ibiza/Ten Story - At The Downlow (Original Mix).mp3" System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Rekordbox Tracks\Toolroom Ibiza\Ten Story - At The Downlow (Original Mix).mp3'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at TagLib.File.LocalFileAbstraction.get_ReadStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()

I cannot remove any cuepoints added by this program.
I cannot create memory points (not clear on how to do this)

Question. Can the phrase "Chorus" be renamed to drop? I can see a function but cant rename.

A UI version would be amazing, id share it with the Rekordbox groups im involved in for sure

Thanks

**Comment by mganss** [comment]
>  Could not find part of the path 1172/1172Error: Error occurred during creation of cues for "9978813" from "G:/Rekordbox Tracks/Toolroom Ibiza/Ten Story - At The Downlow (Original Mix).mp3" System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Rekordbox Tracks\Toolroom Ibiza\Ten Story - At The Downlow (Original Mix).mp3'

Does the file exist at that location? If so, does the user you execute CueGen as have the permission to read the file?

> I cannot remove any cuepoints added by this program. I cannot create memory points (not clear on how to do this)

Use the `-r` option to remove cue points. 

Memory cue points are created by default. If you want to create hot cue points you have to use the `--hc` option.

> Question. Can the phrase "Chorus" be renamed to drop? I can see a function but cant rename.

Yes, use the `-n` option.

> A UI version would be amazing, id share it with the Rekordbox groups im involved in for sure

Thanks. Please vote at #8. Currently, I have no time for this unfortunately, though.
