### ISSUE TITLE
Mac OS Error Message "Error: Error occurred during creation of cues"

### ISSUE THREAD

**Issue by w14e** [mganss/CueGen#2]
Error: Error occurred during creation of cues for "49682660" from "/Users/Anonymous/Downloads/track.mp3" System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at CueGen.Generator.<>c__DisplayClass19_3.<Generate>b__8()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()

I got this for every mp3 file.

**Comment by mganss** [comment]
Please attach one of the .mp3 files to this issue. Thanks.

**Comment by w14e** [comment]
[track.zip](https://github.com/mganss/CueGen/files/6329444/track.zip)

**Comment by mganss** [comment]
Thanks. 1.0.26 should fix this.

**Comment by w14e** [comment]
Sorry, Problem still exist.

**Comment by mganss** [comment]
Strange. Please try again using version 1.0.27 and attach the log file.

**Comment by w14e** [comment]
Now it works perfectly. Thank you very much.
