### ISSUE TITLE
Error - Not valid base64 string

### ISSUE THREAD

**Issue by h00pdie** [mganss/CueGen#24]
Hi, throwing this error on all but 2 songs when I try to add cues:

Error occurred during creation of cues for "96617" from "C:/Users/hears/Desktop/Stuff For LEvels/swedish_house_mafia_-_don't_you_worry_child_(intro_edit).mp3" System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* , Int32 )
   at System.Convert.FromBase64String(String s)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at CueGen.Generator.<>c__DisplayClass20_3.<Generate>b__6()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()

Any clue how to fix this?

**Comment by mganss** [comment]
Can you attach a demo MP3 file here? Thanks.
