### ISSUE TITLE
access to path denied error on macOS

### ISSUE THREAD

**Issue by mrvnklm** [mganss/CueGen#9]
I am getting the following error for every track when using on macOS Monterey, even with sudo:
```
Error: Error occurred during creation of cues for "99638553" from "FILEPATH.mp3" System.UnauthorizedAccessException: Access to the path 'FILEPATH.mp3' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at TagLib.File.LocalFileAbstraction.get_ReadStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Read(ReadStyle propertiesStyle)   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at CueGen.TagFile..ctor(String filePath)
   at CueGen.Content.GetTag()
   at CueGen.Generator.CreateCuesForContent(UInt64& maxId, SQLiteConnection db, Content content)
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at CueGen.Generator.Generate()
```

**Comment by mganss** [comment]
Is Rekordbox running? Or is there any other program running that might have the files open at the same time CueGen is running?

**Comment by mrvnklm** [comment]
No, just rebooted and nothing is running but got the same error.

**Comment by mganss** [comment]
What are the permissions on the files?

**Comment by mrvnklm** [comment]
Thanks for your help, that question helped me find the issue. Somehow my terminal app did not have full disk access so the Documents directory was not readable...
